export enum Command {
    REG = "reg",
    CREATE_GAME = "create_game",
    CREATE_ROOM = "create_room",
    ADD_USER_TO_ROOM = "add_user_to_room",
    ADD_SHIPS = "add_ships",
    ATTACK = "attack",
    FINISH = "finish",
    RANDOM_ATTACK = "randomAttack",
    SINGLE_PLAY = "single_play",
    START_GAME = "start_game",
    TURN = "turn",
    UPDATE_ROOM = "update_room",
    UPDATE_WINNERS = "update_winners",
}
